// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var J,
    __hasProp = {}.hasOwnProperty;

  J = (function() {
    var _getAttribute, _removeAttribute, _setAttribute;
    J = (function() {
      var _arrayOfObjectsConstructor, _createHtmlElementConstructor, _htmlElementConstructor, _selectorConstructor, _voidTag;
      _voidTag = /^<(\w+) \/>$/;
      _createHtmlElementConstructor = function(voidTag) {
        var htmlElement, tagName;
        tagName = voidTag.match(_voidTag)[1];
        htmlElement = document.createElement(tagName);
        return _htmlElementConstructor.call(this, htmlElement);
      };
      _htmlElementConstructor = function(htmlElement) {
        return _arrayOfObjectsConstructor.call(this, [htmlElement]);
      };
      _arrayOfObjectsConstructor = function(objects) {
        return J.merge(this, objects);
      };
      _selectorConstructor = function(selector, context) {
        var _this = this;
        if (context == null) {
          context = [document];
        }
        return J.each(context, function() {
          return _arrayOfObjectsConstructor.call(_this, _this.querySelectorAll(selector));
        });
      };
      return function(selector, context) {
        if (!(this instanceof J)) {
          return new J(selector, context);
        }
        this.length = 0;
        switch (selector) {
          case !(selector != null):
            return this;
          case _voidTag.test(selector):
            return _createHtmlElementConstructor.call(this, selector);
          case selector instanceof HTMLElement:
            return _htmlElementConstructor.call(this, selector);
          case Array.isArray(selector):
            return _arrayOfObjectsConstructor.call(this, selector);
          default:
            return _selectorConstructor.call(this, selector, context);
        }
      };
    })();
    J.repeat = function(string, times) {
      var i, result, _i;
      result = '';
      for (i = _i = 0; 0 <= times ? _i <= times : _i >= times; i = 0 <= times ? ++_i : --_i) {
        result += string;
      }
      return result;
    };
    (function() {
      var _makeMissing;
      _makeMissing = function(string, length, character) {
        if (character == null) {
          character = ' ';
        }
        return J.repeat(character, length - string.length);
      };
      J.padLeft = function(string, length, character) {
        return _makeMissing(string, length, character) + string;
      };
      return J.padRight = function(string, length, character) {
        return string + _makeMissing(string, length, character);
      };
    })();
    (function() {
      var _initialize, _insert, _isArrayLike;
      _isArrayLike = function() {
        return 'length' in this;
      };
      _initialize = function() {
        if (_isArrayLike.call(this)) {
          return [];
        } else {
          return {};
        }
      };
      _insert = function(property, value) {
        if (_isArrayLike.call(this)) {
          return this.push(value);
        } else {
          return this[property] = value;
        }
      };
      J.each = (function() {
        var _eachArray, _eachObject;
        _eachArray = function(callback) {
          var i, _i, _ref;
          for (i = _i = 0, _ref = this.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            if (callback.call(this[i], i) === false) {
              break;
            }
          }
          return this;
        };
        _eachObject = function(callback) {
          var i;
          for (i in this) {
            if (!__hasProp.call(this, i)) continue;
            if (callback.call(this[i], i) === false) {
              break;
            }
          }
          return this;
        };
        return function(object, callback) {
          return (_isArrayLike.call(object) ? _eachArray : _eachObject).call(object, callback);
        };
      })();
      J.map = J.select = function(object, callback) {
        var result;
        result = _initialize.call(object);
        J.each(object, function(i) {
          var mapped;
          mapped = callback.call(this, i);
          return _insert.call(result, i, mapped);
        });
        return result;
      };
      (function() {
        var _invertPredicate;
        _invertPredicate = function(callback) {
          return function() {
            return !callback.apply(this, arguments);
          };
        };
        J.filter = J.where = function(object, callback) {
          var result;
          result = _initialize.call(object);
          J.each(object, function(i) {
            if (callback.call(this, i)) {
              return _insert.call(result, i, this);
            }
          });
          return result;
        };
        J.reject = function(object, callback) {
          return J.filter(object, _invertPredicate(callback));
        };
        J.any = J.some = function(object, callback) {
          var result;
          result = false;
          J.each(object, function(i) {
            if (callback.call(this, i)) {
              result = true;
              return false;
            }
          });
          return result;
        };
        return J.all = J.every = function(object, callback) {
          return !J.any(object, _invertPredicate(callback));
        };
      })();
      J.uniq = function(object) {
        var result;
        result = _initialize.call(object);
        J.each(object, function(i) {
          if (!J.contains(result, this)) {
            return _insert.call(result, i, this);
          }
        });
        return result;
      };
      return J.merge = function(object, elements) {
        J.each(elements, function(i) {
          return _insert.call(object, i, this);
        });
        return object;
      };
    })();
    J.contains = function(object, element) {
      return J.any(object, function() {
        return this === element;
      });
    };
    J.pluck = function(object, property) {
      return J.map(object, function() {
        return this[property];
      });
    };
    (function() {
      var _minMax;
      _minMax = function(callback) {
        var result;
        result = callback();
        J.each(this, function() {
          return result = callback(this, result);
        });
        return result;
      };
      J.min = function(object) {
        return _minMax.call(object, Math.min);
      };
      return J.max = function(object) {
        return _minMax.call(object, Math.max);
      };
    })();
    J.shuffle = (function() {
      var _swap;
      _swap = function(array, i, j) {
        var _ref;
        return _ref = [array[j], array[i]], array[i] = _ref[0], array[j] = _ref[1], _ref;
      };
      return function(array) {
        var i, _i, _ref;
        for (i = _i = _ref = array.length - 1; _ref <= 0 ? _i < 0 : _i > 0; i = _ref <= 0 ? ++_i : --_i) {
          _swap(array, i, J.random(i));
        }
        return array;
      };
    })();
    J.binarySearch = function(array, element) {
      var left, middle, right;
      left = 0;
      middle;

      right = array.length - 1;
      while (left <= right) {
        middle = left + ((right - left) >>> 1);
        switch (false) {
          case !(array[middle] < element):
            left = middle + 1;
            break;
          case !(array[middle] > element):
            right = middle - 1;
            break;
          default:
            return middle;
        }
      }
      return -1;
    };
    J.toArray = function(object) {
      return J.map(object, function() {
        return this;
      });
    };
    J.range = function(min, maxInclusive) {
      var i, result, _i, _results;
      if (arguments.length === 1) {
        return J.range(0, min);
      }
      result = [];
      _results = [];
      for (i = _i = min; min <= maxInclusive ? _i < maxInclusive : _i > maxInclusive; i = min <= maxInclusive ? ++_i : --_i) {
        _results.push(result.push(i));
      }
      return _results;
    };
    J.random = function(min, maxInclusive) {
      var possibleNumbers;
      if (arguments.length === 1) {
        return J.random(0, min);
      }
      possibleNumbers = maxInclusive - min + 1;
      return min + Math.floor(Math.random() * possibleNumbers);
    };
    J.randomByte = function() {
      var decimal;
      decimal = J.random(1 << 8);
      return J.padLeft(decimal.toString(16), 2, '0').toUpperCase();
    };
    J.randomColor = function() {
      var b, g, r;
      r = J.randomByte();
      g = J.randomByte();
      b = J.randomByte();
      return "#" + r + g + b;
    };
    J.get = function(url, callback) {
      var request;
      request = new XMLHttpRequest;
      request.onreadystatechange = function() {
        if (request.readyState === 4) {
          if (request.status === 200) {
            return callback.call(request, request.responseText);
          }
        }
      };
      request.open('GET', url);
      return request.send();
    };
    J.now = function() {
      return +(new Date);
    };
    J.prototype.push = function(element) {
      return this[this.length++] = element;
    };
    J.prototype.get = function(index) {
      if (arguments.length === 0) {
        return J.toArray(this);
      } else {
        return this[index];
      }
    };
    J.prototype.size = function() {
      return this.length;
    };
    (function() {
      var _extendProto;
      _extendProto = function(methodNames, resultFunction) {
        return J.each(methodNames, function() {
          var methodName;
          methodName = this;
          return J.prototype[methodName] = function() {
            var methodArguments, returnedValue;
            methodArguments = J.merge([this], arguments);
            returnedValue = J[methodName].apply(this, methodArguments);
            return resultFunction.call(this, returnedValue);
          };
        });
      };
      (function() {
        var methodNames;
        methodNames = ['each', 'map', 'select', 'any', 'some', 'all', 'every'];
        return _extendProto(methodNames, function(returnedValue) {
          return returnedValue;
        });
      })();
      return (function() {
        var methodNames;
        methodNames = ['filter', 'where', 'reject'];
        return _extendProto(methodNames, function(returnedValue) {
          return new J(returnedValue);
        });
      })();
    })();
    (function() {
      var events;
      events = ['blur', 'focus', 'focusin', 'focusout', 'load', 'resize', 'scroll', 'unload', 'click', 'dblclick', 'mousedown', 'mouseup', 'mousemove', 'mouseover', 'mouseout', 'change', 'select', 'submit', 'keydown', 'keypress', 'keyup', 'error', 'contextmenu'];
      return J.each(events, function() {
        var _this = this;
        return J.prototype[this] = function() {
          var methodArguments;
          methodArguments = J.merge([_this], arguments);
          return J.on(methodArguments);
        };
      });
    })();
    J.prototype.on = function(event, callback) {
      return this.each(function() {
        return this.addEventListener(event, callback);
      });
    };
    J.prototype.mouseenter = function(callback) {
      return this.on('mouseover', callback);
    };
    J.prototype.mouseleave = function(callback) {
      return this.on('mouseout', callback);
    };
    (function() {
      var pairedMethods;
      pairedMethods = {
        prepend: 'prependTo',
        append: 'appendTo',
        before: 'insertBefore',
        after: 'insertAfter'
      };
      return J.each(pairedMethods, function(implementedMethod) {
        return J.prototype[this] = function(elements) {
          elements[implementedMethod](this);
          return this;
        };
      });
    })();
    (function() {
      var _eachEach;
      _eachEach = function(elements, callback) {
        return this.each(function() {
          var parentElement;
          parentElement = this;
          return elements.each(function() {
            return callback.call(parentElement, this);
          });
        });
      };
      J.prototype.prepend = function(elements) {
        return _eachEach.call(this, elements, function(newElement) {
          return this.insertBefore(newElement, this.firstChild);
        });
      };
      J.prototype.append = function(elements) {
        return _eachEach.call(this, elements, function(newElement) {
          return this.appendChild(newElement);
        });
      };
      J.prototype.before = function(elements) {
        return _eachEach.call(this, elements, function(newElement) {
          return this.parentNode.insertBefore(newElement, this);
        });
      };
      return J.prototype.after = function(elements) {
        return _eachEach.call(this, elements, function(newElement) {
          return this.parentNode.insertBefore(newElement, this.nextElementSibling);
        });
      };
    })();
    (function() {
      var _filteredMap;
      _filteredMap = function(callback) {
        var result;
        result = J.map(this, function() {
          return callback.call(this);
        });
        return J.reject(result, function() {
          return this === null;
        });
      };
      J.prototype.prev = function() {
        var result;
        result = _filteredMap.call(this, function() {
          return this.previousElementSibling;
        });
        return new J(result);
      };
      J.prototype.next = function() {
        var result;
        result = _filteredMap.call(this, function() {
          return this.nextElementSibling;
        });
        return new J(result);
      };
      J.prototype.parent = function() {
        var result;
        result = _filteredMap.call(this, function() {
          return this.parentNode;
        });
        result = J.uniq(result);
        return new J(result);
      };
      return J.prototype.children = function() {
        var result;
        result = [];
        J.each(this, function() {
          return J.merge(result, this.children);
        });
        return new J(result);
      };
    })();
    J.prototype.remove = function() {
      return this.each(function() {
        return this.parentNode.removeChild(this);
      });
    };
    _getAttribute = function(attribute) {
      var firstElement;
      firstElement = this[0];
      return firstElement.getAttribute(attribute);
    };
    _setAttribute = function(attribute, value) {
      return this.each(function() {
        return this.setAttribute(attribute, value);
      });
    };
    _removeAttribute = function(attribute) {
      return this.each(function() {
        return this.removeAttribute(attribute);
      });
    };
    J.prototype.attr = function(attribute, value) {
      if (arguments.length === 1) {
        return _getAttribute.call(this, attribute);
      } else {
        return _setAttribute.call(this, attribute, value);
      }
    };
    J.prototype.removeAttr = function(attribute) {
      return _removeAttribute.call(this, attribute);
    };
    (function() {
      var _getData, _getDataProperty, _hasDataProperty, _parseDataAttribute, _setData, _setDataProperty;
      _parseDataAttribute = function(key) {
        var valueString;
        valueString = this.dataset[key];
        if (!(key in this.dataset)) {
          return undefined;
        }
        if (parseFloat(valueString).toString() === valueString) {
          return parseFloat(valueString);
        }
        if (valueString === 'true') {
          return true;
        }
        if (valueString === 'false') {
          return false;
        }
        if (valueString === 'null') {
          return null;
        }
        try {
          return JSON.parse(valueString);
        } catch (e) {
          return valueString;
        }
      };
      _hasDataProperty = function(key) {
        return this._data && (key in this._data);
      };
      _getDataProperty = function(key) {
        return this._data[key];
      };
      _setDataProperty = function(key, value) {
        this._data = this._data || {};
        return this._data[key] = value;
      };
      _getData = function(key) {
        var firstElement;
        firstElement = this[0];
        if (_hasDataProperty.call(firstElement, key)) {
          return _getDataProperty.call(firstElement, key);
        } else {
          return _parseDataAttribute.call(firstElement, key);
        }
      };
      _setData = function(key, value) {
        return this.each(function() {
          return _setDataProperty.call(this, key, value);
        });
      };
      J.prototype.data = function(key, value) {
        if (arguments.length === 1) {
          return _getData.call(this, key);
        } else {
          return _setData.call(this, key, value);
        }
      };
      return J.prototype.removeData = function(key) {
        return J.prototype.data.call(this, key, undefined);
      };
    })();
    J.prototype.hasClass = function(className) {
      return this.any(function() {
        return this.classList.contains(className);
      });
    };
    J.prototype.addClass = function(className) {
      return this.each(function() {
        return this.classList.add(className);
      });
    };
    J.prototype.removeClass = function(className) {
      return this.each(function() {
        return this.classList.remove(className);
      });
    };
    J.prototype.toggleClass = function(className) {
      return this.each(function() {
        return this.classList.toggle(className);
      });
    };
    (function() {
      var _getCss, _makeVendorProperty, _setCss;
      _makeVendorProperty = (function() {
        var _style, _vendorPrefixes;
        _vendorPrefixes = ['Webkit', 'Moz', 'ms', 'O'];
        _style = document.createElement('div').style;
        return function(camelCasedProperty) {
          var pascalCasedProperty;
          if (camelCasedProperty in _style) {
            return camelCasedProperty;
          }
          pascalCasedProperty = camelCasedProperty[0].toUpperCase() + camelCasedProperty.substr(1);
          vendorProperty;

          J.each(_vendorPrefixes, function() {
            var vendorProperty;
            vendorProperty = this + pascalCasedProperty;
            if (vendorProperty in _style) {
              return false;
            }
            return vendorProperty = void 0;
          });
          return vendorProperty;
        };
      })();
      _getCss = function(property) {
        var firstElement;
        firstElement = this[0];
        return getComputedStyle(firstElement)[property];
      };
      _setCss = function(property, value) {
        return this.each(function() {
          return this.style[property] = value;
        });
      };
      return J.prototype.css = function(camelCasedProperty, value) {
        var property;
        property = _makeVendorProperty(camelCasedProperty);
        return (arguments.length === 1 ? _getCss : _setCss).call(this, property, value);
      };
    })();
    (function() {
      var _isHidden, _showHide;
      _isHidden = function() {
        return this.css('display') === 'none';
      };
      _showHide = function(show) {
        return this.css('display', (show ? 'block' : 'none'));
      };
      J.prototype.show = function() {
        return _showHide.call(this, true);
      };
      J.prototype.hide = function() {
        return _showHide.call(this, false);
      };
      return J.prototype.toggle = function() {
        return this.each(function() {
          var self;
          self = new J(this);
          return _showHide.call(self, _isHidden.call(self));
        });
      };
    })();
    (function() {
      var _getText, _setText;
      _getText = function() {
        var firstElement;
        firstElement = this[0];
        return firstElement.textContent;
      };
      _setText = function(text) {
        return this.each(function() {
          return this.textContent = text;
        });
      };
      return J.prototype.text = function(text) {
        return (arguments.length === 0 ? _getText : _setText).call(this, text);
      };
    })();
    (function() {
      var _getHtml, _setHtml;
      _getHtml = function() {
        var firstElement;
        firstElement = this[0];
        return firstElement.innerHTML;
      };
      _setHtml = function(html) {
        return this.each(function() {
          return this.innerHTML = html;
        });
      };
      return J.prototype.html = function(html) {
        return (arguments.length === 0 ? _getHtml : _setHtml).call(this, html);
      };
    })();
    return J;
  })();

}).call(this);
